
name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger this workflow when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The OS on which the workflow will run

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This step checks out your repository code

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0  # This action sets up SSH agent
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Uses the SSH private key you stored in GitHub Secrets

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r ./pruthvithada ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu
